repos:
  - repo: local
    hooks:
      - id: typstyle
        name: typstyle
        description: Format Typst files with typstyle
        entry: typstyle
        language: system
        files: \.typ$
        args: ["-i"]
